hexapod_controller:
  ros__parameters:
    dt: 0.01
    pid:
      bias:
        Ax: 0.036758759765625
        Ay: 0.08942044921874998
        Az: 0.15912333496094355
        Gx: 0.23928244274809013
        Gy: 0.5240763358778625
        Gz: 0.03676335877862609
        calibrated: 1
        count: 500
        pitch: 0.21829648314920663
        roll: 0.5310408175278014
      pitch:
        filter_coe: 0.95
        kd: 0.03
        ki: 0.1
        kp: 1.5
        max_I: 40
        max_angle: 60
      roll:
        filter_coe: 0.95
        kd: 0.03
        ki: 0.1
        kp: 1.5
        max_I: 40
        max_angle: 60
      yaw:
        kd: 0
        ki: 0.2
        kp: 2
        max_I: 10
        max_angle: 20
