hexapod_controller:
  ros__parameters:
    dt: 0.002
    pid:
      bias:
        Ax: 0.15234479736328116
        Ay: 0.04347918457031242
        Az: 0.4238592138672068
        Gx: 0.214702290076337
        Gy: 0.5318320610687004
        Gz: 0.03808396946564884
        calibrated: 1
        count: 1000
        pitch: 0.9301980087972117
        roll: 0.2654676736333702
      pitch:
        filter_coe: 0.95
        kd: 0.005
        ki: 0.2
        kp: 3
        max_I: 40
        max_angle: 60
      roll:
        filter_coe: 0.95
        kd: 0.005
        ki: 0.2
        kp: 3
        max_I: 40
        max_angle: 60
      yaw:
        kd: 0
        ki: 0
        kp: 1
        max_I: 10
        max_angle: 20
